# Generated by Django 4.2.6 on 2023-11-11 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_back', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=300)),
                ('tel', models.CharField(max_length=45)),
                ('birth', models.DateField()),
                ('username', models.ForeignKey(max_length=45, on_delete=django.db.models.deletion.CASCADE, to='django_back.user')),
            ],
        ),
    ]
