# Generated by Django 4.2.6 on 2023-11-02 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hashtag', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='name',
            field=models.TextField(default=' '),
        ),
    ]
